/*
 * This source file was generated by the Gradle 'init' task
 */
package com.lazaroofarrill;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.time.Instant;
import java.time.temporal.ChronoUnit;
import java.util.ArrayList;
import java.util.UUID;

class ScoreboardTest {
  @Test
  void machesAreStartedCorrectly() {
    var scoreBoard = new Scoreboard();
    var home = "Home";
    var away = "Away";

    var startTime = Instant.now();

    scoreBoard.startMatch(home, away, startTime);

    assertEquals(scoreBoard.matches.size(), 1);
    assertEquals(scoreBoard.matches.getFirst().home().name(), home);
    assertEquals(scoreBoard.matches.getFirst().away().name(), away);
    assertEquals(scoreBoard.matches.getFirst().startedAt(), startTime);
    assertEquals(scoreBoard.matches.getFirst().home().points(), 0);
    assertEquals(scoreBoard.matches.getFirst().away().points(), 0);
  }

  @Test
  void aMatchScoreCanBeUpdated() {
    var scoreBoard = new Scoreboard();

    var matchId = scoreBoard.startMatch("home", "away", Instant.now());

    scoreBoard.updateScores(matchId, 5, 4);

    assertEquals(scoreBoard.matches.size(), 1);
    assertEquals(scoreBoard.matches.getFirst().home().points(), 5);
    assertEquals(scoreBoard.matches.getFirst().away().points(), 4);
  }

  @Test
  void matchesAreStoredSortedByPointSumAndThenReverseStartTime() {
    var scoreBoard = new Scoreboard();
    var leagueStart = Instant.now();

    var mexicoVSCanada = scoreBoard.startMatch("Mexico", "Canada", leagueStart);
    scoreBoard.updateScores(mexicoVSCanada, 0, 5);

    var spainVSBrazil = scoreBoard.startMatch("Spain", "Brazil", leagueStart.plus(1, ChronoUnit.MINUTES));
    scoreBoard.updateScores(spainVSBrazil, 10, 2);

    var germanyVsFrance = scoreBoard.startMatch("Germany", "France", leagueStart.plus(2, ChronoUnit.MINUTES));
    scoreBoard.updateScores(germanyVsFrance, 2, 2);

    var uruguayVsItaly = scoreBoard.startMatch("Uruguay", "Italy", leagueStart.plus(3, ChronoUnit.MINUTES));
    scoreBoard.updateScores(uruguayVsItaly, 6, 6);
    var argentinaVsAustralia = scoreBoard.startMatch("Argentina", "Australia", leagueStart.plus(4, ChronoUnit.MINUTES));
    scoreBoard.updateScores(argentinaVsAustralia, 3, 1);

    var matches = new ArrayList<>(scoreBoard.matches);
    for (TeamMatch match : matches) {
      System.out.printf("%s(%d) --- %s(%d)\n",
        match.home().name(),
        match.away().name());

    }
    assertEquals(matches.get(0).matchId(), uruguayVsItaly);
  }
}
