/*
 * This source file was generated by the Gradle 'init' task
 */
package com.lazaroofarrill;

import java.time.Instant;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.TreeSet;
import java.util.UUID;

public class InMemoryScoreboard implements Scoreboard {
  private TreeSet<TeamMatch> matches = new TreeSet<>(
      Comparator
          .comparingInt((TeamMatch t) -> t.home().points() + t.away().points()).reversed()
          .thenComparing(Comparator.comparing(TeamMatch::startedAt).reversed())
          .thenComparing(TeamMatch::matchId)); // Final segregator

  public UUID startMatch(String home, String away) {
    var uuid = UUID.randomUUID();
    var match = new TeamMatch(
        new Team(home, 0),
        new Team(away, 0),
        Instant.now(),
        uuid);
    matches.add(match);
    return uuid;
  }

  public void updateScores(UUID matchId, int homeScore, int awayScore) {
    var target = findTeamMatch(matchId);

    matches.remove(target);
    matches.add(new TeamMatch(target.home().withPoints(homeScore),
        target.away().withPoints(awayScore), target.startedAt(), target.matchId()));
  }

  @Override
  public void finishMatch(UUID matchId) {
    matches.remove(findTeamMatch(matchId));
  }

  @Override
  public List<TeamMatch> getSummary() {
    return new ArrayList<>(matches);
  }

  private TeamMatch findTeamMatch(UUID matchId) {
    return matches.stream()
        .filter(t -> t.matchId().equals(matchId))
        .findFirst()
        .orElseThrow(() -> new IllegalArgumentException("The match with the requested ID was not found"));
  }
}

record Team(String name, int points) {
  public Team(String name, int points) {
    if (name.trim().equals("")) {
      throw new IllegalArgumentException("Name may not be blank");
    }
    if (points < 0) {
      throw new IllegalArgumentException("Points may not be negative");
    }
    this.name = name;
    this.points = points;
  }

  public Team withPoints(int newPoints) {
    if (newPoints < 0) {
      throw new IllegalArgumentException("Points cannot be negative");
    }
    return new Team(this.name, newPoints);
  }
}

record TeamMatch(Team home, Team away, Instant startedAt, UUID matchId) {
}
