/*
 * This source file was generated by the Gradle 'init' task
 */
package com.lazaroofarrill;

import java.time.Clock;
import java.time.Instant;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.TreeSet;
import java.util.UUID;

public class InMemoryScoreboard implements Scoreboard {
  private final Clock clock;

  private final TreeSet<TeamMatch> matches = new TreeSet<>(
      Comparator
          .comparingInt((TeamMatch t) -> t.home().points() + t.away().points()).reversed()
          .thenComparing(Comparator.comparing(TeamMatch::startedAt).reversed())
          .thenComparing(TeamMatch::matchId)); // Final segregator

  public  InMemoryScoreboard() {
    this.clock = Clock.systemUTC();
  }
  public  InMemoryScoreboard(Clock clock) {
    this.clock = clock;
  }

  public UUID startMatch(String home, String away) {
    var uuid = UUID.randomUUID();
    var match = new TeamMatch(
        new Team(home, 0),
        new Team(away, 0),
        Instant.now(clock),
        uuid);
    matches.add(match);
    return uuid;
  }

  public void updateScores(UUID matchId, int homeScore, int awayScore) {
    var target = findTeamMatch(matchId);

    matches.remove(target);
    matches.add(new TeamMatch(target.home().withPoints(homeScore),
        target.away().withPoints(awayScore), target.startedAt(), target.matchId()));
  }

  @Override
  public void finishMatch(UUID matchId) {
    matches.remove(findTeamMatch(matchId));
  }

  @Override
  public List<TeamMatch> getSummary() {
    return new ArrayList<>(matches);
  }

  private TeamMatch findTeamMatch(UUID matchId) {
    return matches.stream()
        .filter(t -> t.matchId().equals(matchId))
        .findFirst()
        .orElseThrow(() -> new IllegalArgumentException("The match with the requested ID was not found"));
  }
}
