/*
 * This source file was generated by the Gradle 'init' task
 */
package com.lazaroofarrill;

import java.time.Instant;
import java.util.Comparator;
import java.util.TreeSet;
import java.util.UUID;

record Team(String name, int points) {
  public Team(String name, int points) {
    if (name.trim().equals("")) {
      throw new IllegalArgumentException("Name may not be blank");
    }
    if (points < 0) {
      throw new IllegalArgumentException("Points may not be negative");
    }
    this.name = name;
    this.points = points;
  }

  public Team withPoints(int newPoints) throws IllegalArgumentException {
    if (newPoints < 0) {
      throw new IllegalArgumentException("Points cannot be negative");
    }
    return new Team(this.name, newPoints);
  }
}

record TeamMatch(Team home, Team away, Instant startedAt, UUID matchId) {
}

public class Scoreboard {
  TreeSet<TeamMatch> matches = new TreeSet<>(
      Comparator
          .comparingInt((TeamMatch t) -> t.home().points() + t.away().points())
          .thenComparing(TeamMatch::startedAt)
          .thenComparing(TeamMatch::matchId));

  public UUID startMatch(String home, String away, Instant time) {
    var uuid = UUID.randomUUID();
    var match = new TeamMatch(
        new Team(home, 0),
        new Team(away, 0),
        time,
        uuid);
    matches.add(match);
    return uuid;
  }

  public void updateScores(UUID matchId, int homeScore, int awayScore) {
    var target = matches.stream()
        .filter(t -> t.matchId().equals(matchId))
        .findFirst().orElse(null);

    if (target == null) {
      throw new IllegalArgumentException("The match with the requested ID was not found");
    }

    matches.remove(target);
    matches.add(new TeamMatch(target.home().withPoints(homeScore),
        target.away().withPoints(awayScore), target.startedAt(), target.matchId()));
  }
}
